### PR TITLE
Microverse Project - Building Responsive Design of "The News Week" Home Page 

### PR DESCRIPTION
**Pull request by karthykarthick**
In this project, we designed a clone of the www.thenewsweek.com home page.

We Implement responsiveness for the screen sizes:
- sass
- 7-1 pattern for our files
- BIM for naming our class
- Bootstrap

And media query for
- Small screens
- Medium size screens and
- Larger screen sizes

We have also implemented gradients on some of the necessary background images.

### CODE REVIEW

**Comment by bertil291utn** [comment]
**Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below: 

- [x] Should be white color, weather info, and log in text

image

### Small screen

Check the original page with a small screen to accomplish all these requirements

**Navbar**

- [x] It has no burger icon
- [x] Logo should be to the left
- [x] Take in mind your right margin

image

- [x] **TOP STORY SECTION** should be first then **FEATURE STORIES** one

image

- [x] Category tag has less width

- [x] Title should bolder and with a larger font-size.

- [x] Change italic style to the title

  image

  - [x] Your order it's not same as the original page, please make all changes according these order
    - Top story
    - Featured stories
    - The debate
    - Opinion
    - More stories
    - My turn
    - Culture & travel
    - In the magazine
    - Editors pick
    - Section pick (No title)
    - Footer

### Medium screen

- [x] Should have two columns
- [x] Work on the details (margin, colors, fonts, fonts styles, etc) you should approach a clone web page

|                       ACTUAL WEB PAGE                        |                            YOURS                             |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| image | image |



### Large screen

- [x] Open the original page check all the details (margin, colors, fonts, fonts styles) should be the same with your page.

image



### Summary

I suggest to you guys open the actual page clone an exact web page with all details, just when you're sure then send for another code review.

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Good job so far team, :warning: I have noticed that you have skipped some of the requirements of the previews TSE please return back and do them.

### Please make the required changes before you submit another code review.
## Happy Coding :tophat:

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle:
**Hello @MohameDawood @karthy1998** 
Good job so far with your project :muscle:   
Please, make sure to do the improvements required for the previous TSE. Here some additional changes to do:
- [x]  in medium screen size, "my turn" section should be three columns, not one
- [x] in medium screen size, "CULTURE & TRAVEL" section should be three columns, not one
- [x] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.
- [x] look at the "opinion" section in medium and small screen size, the article's title must be at the right side of the picture, not below.
- [x]  you have two "editor's pick" titles, change the first one for "IN THE MAGAZINE"
- [x] Newsweek cover page should appear inside "IN THE MAGAZINE" section


Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Comment by andresporras3423** [comment]
### FOR THE NEXT TSE
I'm sorry, by mistake I approved the project when submitting the form of this last review. Please forgive students for the fact that PR is already merged.

Thank you,

Oscar Andrés Russi Porras

**Pull request merged**
